version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        BUILD_FOLDER: "dist"
phases:
    install:
        runtime-versions:
            nodejs: 18
    commands:
        - echo Installing source NPM dependencies...
        - npm config set legacy-peer-deps true
        - pwd
        - ls -l
        - npm install
        - npm install -g @angular/cli
        - ls -l
    build:
        commands:
            - echo Build started 
            - ng build
            # - cp -R node_modules/ dist/node_modules
            # - cd dist
            # - ls -l
            # - more server.js
    post-build:
        commands:
            - cp -R node_modules/ dist/node_modules
            - ls -l
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes